=== DiSSCo/openDS/data-model/fdo-type/create-update-tombstone-event/0.3.0/schema/create-update-tombstone-event.json
{
  "$id": "https://schemas.dissco.tech/schemas/fdo-type/create-update-delete-tombstone-event/0.3.0/create-update-delete-tombstone-event.json",
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$comment": "Create Update Tombstone Event Version 0.3.0",
  "title": "CreateUpdateTombstoneEvent",
  "type": "object",
  "properties": {
    "@id": {
      "type": "string",
      "description": "The unique identifier of the Create Update Tombstone Event, this includes the version of the object",
      "examples": [
        "https://hdl.handle.net/20.5000.1025/XXX-XXX-XXX/3",
        "https://doi.org/TEST/PGD-QGK-S0R/1"
      ]
    },
    "@type": {
      "type": "string",
      "description": "The type of the object, in this case ods:CreateUpdateTombstoneEvent",
      "const": "ods:CreateUpdateTombstoneEvent"
    },
    "ods:ID": {
      "type": "string",
      "description": "The unique identifier of the Create Update Tombstone Event, this includes the version of the object",
      "examples": [
        "https://hdl.handle.net/20.5000.1025/XXX-XXX-XXX/3",
        "https://doi.org/TEST/PGD-QGK-S0R/1"
      ]
    },
    "ods:type": {
      "type": "string",
      "description": "The DOI to the FDO type of the object",
      "pattern": "^https:\/\/doi\\.org\/[\\w\\.]+/[\\w\\.]+",
      "examples": [
        "https://doi.org/10.15468/1a2b3c"
      ]
    },
    "prov:Activity": {
      "type": "object",
      "description": "Based on the prov-ontology Activity Class, https://www.w3.org/ns/prov#Activity",
      "properties": {
        "@id": {
          "type": "string",
          "description": "The unique identifier of the Activity, this is a generated uuid (generated by the provenance service)",
          "examples": [
            "7ba628d4-2e28-4ce4-ad1e-e99c97c20507",
            "807f145c-11a1-41f0-af34-b2d7c580bcc1"
          ]
        },
        "@type": {
          "description": "The type of the activity",
          "enum": [
            "ods:Create",
            "ods:Update",
            "ods:Tombstone"
          ]
        },
        "prov:wasAssociatedWith": {
          "type": "array",
          "description": "Contains zero a reference to one or more prov:Agent objects that were associated with the Activity",
          "items": {
            "type": "object",
            "properties": {
              "@id": {
                "type": "string",
                "description": "The unique identifier of the prov:Agent that was associated with the Activity (as indicated at @id in the Activity Class), http://www.w3.org/ns/prov#wasAssociatedWith",
                "examples": [
                  "https://orcid.org/0000-0002-1825-0097",
                  "https://hdl.handle.net/20.5000.1025/XXX-XXX-XXX"
                ]
              },
              "prov:hadRole": {
                "enum": [
                  "ods:Approver",
                  "ods:Requestor",
                  "ods:Generator"
                ],
                "description": "The role of the agent in the activity"
              }
            },
            "required": [
              "@id"
            ],
            "additionalProperties": false
          }
        },
        "prov:endedAtTime": {
          "type": "string",
          "format": "date-time",
          "description": "The date and time when the activity ended, in ISO 8601 format, http://www.w3.org/ns/prov#endedAtTime",
          "examples": [
            "2024-06-11T09:14:001Z"
          ]
        },
        "prov:used": {
          "type": "string",
          "description": "The unique identifier of the prov:Entity that was used in the Activity (as indicated at @id in the Activity Class), http://www.w3.org/ns/prov#used",
          "examples": [
            "https://hdl.handle.net/20.5000.1025/XXX-XXX-XXX/1",
            "https://doi.org/10.15468/1a2b3c/3"
          ]
        },
        "rdfs:comment": {
          "type": "string",
          "description": "A comment about the activity, https://www.w3.org/2000/01/rdf-schema#comment",
          "examples": [
            "This activity was created by the user"
          ]
        },
        "ods:changeValue": {
          "type": "array",
          "items": {
            "type": "object"
          },
          "description": "The json patch object that describes the changes made to the object as opposed to the previous version, empty if this is a ods:Create or ods:Tombstone activity",
          "examples": [
            [
              {
                "op": "add",
                "path": "/ods:attributes/dwc:collectionId",
                "value": "Herbarium Berolinense"
              },
              {
                "op": "copy",
                "path": "/ods:attributes/dwc:identification/0/taxonIdentifications/0/dwc:infragenericEpithet",
                "from": "/ods:attributes/dwc:identification/0/taxonIdentifications/0/dwc:specificEpithet"
              }
            ]
          ]
        }
      },
      "required": [
        "@id",
        "@type",
        "prov:wasAssociatedWith",
        "prov:endedAtTime",
        "prov:used"
      ],
      "additionalProperties": false
    },
    "prov:Entity": {
      "type": "object",
      "description": "Based on the prov-ontology Entity Class, https://www.w3.org/ns/prov#Entity",
      "properties": {
        "@id": {
          "type": "string",
          "description": "The unique identifier of the Create Update Tombstone Event, this includes the version of the object",
          "examples": [
            "https://hdl.handle.net/20.5000.1025/XXX-XXX-XXX/3",
            "https://doi.org/TEST/PGD-QGK-S0R/1"
          ]
        },
        "@type": {
          "type": "string",
          "description": "The type of the ods type of the entity. This provides information about the structure of the `prov:value` field",
          "examples": [
            "ods:DigitalSpecimen",
            "ods:SourceSystem"
          ]
        },
        "prov:value": {
          "type": "object",
          "description": "The full object that is the result of the prov:Activity, the structure of this object is defined by the `@type` field. When the `prov:Activity` is of type `ods:Tombstone`, this field is empty",
          "examples": [
            {
              "@id": "https://hdl.handle.net/20.5000.1025/ABC-DEF-GHI",
              "@type": "ods:Mapping",
              "ods:ID": "https://hdl.handle.net/20.5000.1025/ABC-DEF-GHI",
              "ods:type": "https://doi.org/10.15468/1a2b3c",
              "schema:version": 1,
              "schema:name": "Default Mapping for Herbarium of University of Coimbra (COI)",
              "schema:description": "The default mapping for the Herbarium of the University of Coimbra (COI) to the Darwin Core standard.",
              "schema:dateCreated": "2021-06-01T12:00:00Z",
              "ods:creator": "e2befba6-9324-4bb4-9f41-d7dfae4a44b0",
              "ods:Mapping": {
                "ods:DefaultMapping": [
                  {
                    "ods:physicalSpecimenIdType": "cetaf"
                  },
                  {
                    "ods:type": "ZoologyVertebrateSpecimen"
                  },
                  {
                    "ods:organisationId": "https://ror.org/05xg72x27"
                  }
                ],
                "ods:FieldMapping": [
                  {
                    "ods:physicalSpecimenId": "dwc:catalogNumber"
                  }
                ]
              },
              "ods:mappingDataStandard": "dwc"
            }
          ]
        },
        "prov:wasRevisionOf": {
          "type": "string",
          "description": "The unique identifier (handle) of the previous version of the object, only present when prov:Activity is of type ods:Update and ods:Tombstone",
          "examples": [
            "https://hdl.handle.net/20.5000.1025/XXX-XXX-XXX/1"
          ]
        },
        "prov:wasGeneratedBy": {
          "type": "string",
          "description": "The unique identifier of the prov:Activity that generated the Entity (as indicated at @id in the Activity Class), http://www.w3.org/ns/prov#wasGeneratedBy",
          "examples": [
            "7ba628d4-2e28-4ce4-ad1e-e99c97c20507",
            "807f145c-11a1-41f0-af34-b2d7c580bcc1"
          ]
        }
      },
      "required": [
        "@id",
        "@type",
        "prov:wasGeneratedBy"
      ],
      "additionalProperties": false
    },
    "ods:hasProvAgent": {
      "type": "array",
      "description": "Contains zero or more prov:Agent objects",
      "items": {
        "type": "object",
        "description": "Based on the prov-ontology Agent Class, https://www.w3.org/ns/prov#Agent",
        "$ref": "https://schemas.dissco.tech/schemas/fdo-type/shared-model/0.3.0/agent.json"
      }
    }
  }
}

=== DiSSCo/openDS/data-model/fdo-type/create-update-tombstone-event/0.3.0/examples/create-event-example.json
{
  "@id": "https://doi.org/TEST/PGD-QGK-S0R/1",
  "@type": "ods:CreateUpdateTombstoneEvent",
  "ods:ID": "https://doi.org/TEST/PGD-QGK-S0R/1",
  "ods:type": "https://doi.org/10.15468/1a2b3c",
  "prov:Activity": {
    "@id": "7ba628d4-2e28-4ce4-ad1e-e99c97c20507",
    "@type": "ods:Create",
    "prov:wasAssociatedWith": [
      {
        "@id": "https://orcid.org/0000-0002-1825-0097",
        "prov:hadRole": "ods:Approver"
      },
      {
        "@id": "https://hdl.handle.net/20.5000.1025/XXX-XXX-XXX",
        "prov:hadRole": "ods:Requestor"
      },
      {
        "@id": "https://hdl.handle.net/20.5000.1025/XXX-YYY-XXX",
        "prov:hadRole": "ods:Generator"
      }
    ],
    "prov:endedAtTime": "2024-06-11T09:14:00.348Z",
    "prov:used": "https://doi.org/10.15468/1a2b3c/3",
    "rdfs:comment": "This activity was created by the user",
    "ods:changeValue": []
  },
  "prov:Entity": {
    "@id": "https://doi.org/TEST/PGD-QGK-S0R/1",
    "@type": "ods:DigitalSpecimen",
    "prov:value": {
      "@id": "https://hdl.handle.net/20.5000.1025/ABC-DEF-GHI",
      "@type": "ods:Mapping",
      "ods:ID": "https://hdl.handle.net/20.5000.1025/ABC-DEF-GHI",
      "ods:type": "https://doi.org/10.15468/1a2b3c",
      "schema:version": 1,
      "schema:name": "Default Mapping for Herbarium of University of Coimbra (COI)",
      "schema:description": "The default mapping for the Herbarium of the University of Coimbra (COI) to the Darwin Core standard.",
      "schema:dateCreated": "2021-06-01T12:00:00.676Z",
      "ods:creator": "e2befba6-9324-4bb4-9f41-d7dfae4a44b0",
      "ods:Mapping": {
        "ods:DefaultMapping": [
          {
            "ods:physicalSpecimenIDType": "Global"
          },
          {
            "ods:type": "ZoologyVertebrateSpecimen"
          },
          {
            "ods:organisationId": "https://ror.org/05xg72x27"
          }
        ],
        "ods:FieldMapping": [
          {
            "ods:physicalSpecimenId": "dwc:catalogNumber"
          }
        ]
      },
      "ods:mappingDataStandard": "dwc"
    },
    "prov:wasGeneratedBy": "7ba628d4-2e28-4ce4-ad1e-e99c97c20507"
  },
  "ods:hasProvAgent": [
    {
      "@id": "https://orcid.org/0000-0002-1825-0097",
      "@type": "prov:Person",
      "schema:name": "John Doe"
    },
    {
      "@id": "https://hdl.handle.net/20.5000.1025/XXX-XXX-XXX",
      "@type": "prov:SoftwareAgent",
      "schema:name": "GBIF Linker Service"
    },
    {
      "@id": "https://hdl.handle.net/20.5000.1025/XXX-YYY-XXX",
      "@type": "prov:SoftwareAgent",
      "schema:name": "Digital Specimen Processor"
    }
  ]
}
