=== DiSSCo/openDS/data-model/fdo-type/virtual-collection/0.1.0/schema/virtual-collection.json
{
  "$id": "https://schemas.dissco.tech/schemas/fdo-type/virtual-collection/0.1.0/virtual-collection.json",
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$comment": "DigitalObject Version 0.1.0",
  "title": "VirtualCollection",
  "type": "object",
  "properties": {
    "@id": {
      "type": "string",
      "description": "The PID of the object in the form of a handle, which is also the URL to the object.",
      "pattern": "^https:\/\/doi\\.org\/[\\w\\.]+/(\\w){3}-(\\w){3}-(\\w){3}",
      "examples": [
        "https://hdl.handle.net/20.5000.1025/XXX-XXX-XXX"
      ]
    },
    "@type": {
      "type": "string",
      "description": "The type of the object, which is always VirtualCollection.",
      "const": "VirtualCollection",
      "examples": [
        "VirtualCollection"
      ]
    },
    "dcterms:identifier": {
      "type": "string",
      "description": "PID of the object.",
      "pattern": "^https:\/\/doi\\.org\/[\\w\\.]+/(\\w){3}-(\\w){3}-(\\w){3}",
      "examples": [
        "https://hdl.handle.net/20.5000.1025/XXX-XXX-XXX"
      ]
    },
    "ods:fdoType": {
      "type": "string",
      "description": "The Handle to the FDO type of the object",
      "pattern": "^https:\/\/hdl\\.handle\\.net\/[\\w.]+\/(.){3}-(.){3}-(.){3}",
      "examples": [
        "https://hdl.handle.net/21.T11148/2ac65a933b7a0361b651"
      ]
    },
    "ods:status": {
      "type": "string",
      "enum": [
        "Draft",
        "Active",
        "Tombstone"
      ],
      "description": "The status of the Digital Object. A digital object can be in Draft, when it is not published yet. Active when it is published and the object is active and Tombstone which means the object has been archived."
    },
    "schema:version": {
      "type": "integer",
      "minimum": 1,
      "description": "The version of the object, each change generates a new version. The version starts at 1 and each change will increment the version number with 1",
      "examples": [
        1,
        2,
        3
      ]
    },
    "ltc:collectionName": {
      "type": "string",
      "description": "A short title that summarizes the collection objects contained in the virtual collection.",
      "examples": [
        "Bumblebee Collection of South Holland"
      ]
    },
    "ltc:description": {
      "type": "string",
      "description": "A description or narrative about the collection.",
      "examples": [
        "A virtual reference collection including key bumblebee specimens"
      ]
    },
    "ltc:basisOfScheme": {
      "type": "string",
      "description": "This property is intended to summarise the reason for grouping a number of objects together.",
      "enum": [
        "Reference Collection",
        "Community Collection"
      ]
    },
    "schema:dateCreated": {
      "type": "string",
      "description": "Timestamp of creation. Internally generated, https://schema.org/dateCreated",
      "format": "date-time",
      "examples": [
        "2021-06-01T12:00:00.323Z"
      ]
    },
    "schema:dateModified": {
      "type": "string",
      "description": "Timestamp of last modification. Internally generated, follows the ISO Date Time Format yyyy-MM-dd'T'HH:mm:ss.SSSXXX",
      "format": "date-time",
      "examples": [
        "2021-06-06T13:22:00.445Z"
      ]
    },
    "schema:contentURL": {
      "type": "string",
      "description": "URI for a media item that is representative for the virtual collection",
      "examples": [
        "https://image.bgbm.org/images/internal/HerbarThumbs/B100272813_1700",
        "https://medialib.naturalis.nl/file/id/RGM.924559/format/large"
      ]
    },
    "schema:creator": {
      "type": "object",
      "description": "Contains an ods:Agent object",
      "$ref": "https://schemas.dissco.tech/schemas/fdo-type/shared-model/0.4.0/agent.json"
    },
    "ods:hasTargetDigitalObjectFilter": {
      "type": "object",
      "description": "Contains the filters that the collection uses",
      "$ref": "https://schemas.dissco.tech/schemas/fdo-type/shared-model/0.4.0/target-digital-object-filter.json"
    },
    "ods:hasTombstoneMetadata": {
      "type": "object",
      "description": "Object containing the tombstone metadata of the object. Only present when ods:status is ods:Tombstone",
      "$ref": "https://schemas.dissco.tech/schemas/fdo-type/shared-model/0.4.0/tombstone-metadata.json"
    }
  },
  "required": [
    "@id",
    "@type",
    "dcterms:identifier",
    "ods:fdoType",
    "ods:status",
    "schema:version",
    "ltc:collectionName",
    "ltc:basisOfScheme",
    "ods:hasTargetDigitalObjectFilter",
    "schema:dateCreated",
    "schema:creator"
  ],
  "additionalProperties": false
}

=== DiSSCo/openDS/data-model/fdo-type/virtual-collection/0.1.0/examples/virtual-reference-ids-collection.json
{
  "@id": "https://doi.org/TEST/WDR-Y9G-2AY",
  "@type": "VirtualCollection",
  "dcterms:identifier": "https://doi.org/TEST/WDR-Y9G-2AY",
  "ods:fdoType": "https://hdl.handle.net/21.T11148/2ac65a933b7a0361b651",
  "ods:status": "Active",
  "schema:version": 1,
  "ltc:collectionName": "Holotypes Botany Collection",
  "ltc:description": "A virtual collection of specific botanical holotypes. Excluding the Naturalis collections.",
  "ltc:basisOfScheme": "Reference Collection",
  "schema:contentURL": "https://image.bgbm.org/images/internal/HerbarThumbs/B100272813_1700",
  "schema:dateCreated": "2025-03-01T12:00:00.323Z",
  "schema:creator": {
    "@id": "https://orcid.org/0000-0002-5669-2769",
    "@type": "schema:Person",
    "schema:name": "Sam Leeflang",
    "ods:hasIdentifiers": [
      {
        "@id": "https://orcid.org/0000-0002-5669-2769",
        "@type": "ods:Identifier",
        "dcterms:title": "ORCID",
        "dcterms:type": "URL",
        "dcterms:identifier": "https://orcid.org/0000-0002-5669-2769",
        "ods:gupriLevel": "GloballyUniqueStablePersistentResolvable",
        "ods:identifierStatus": "Preferred"
      }
    ]
  },
  "ods:hasTargetDigitalObjectFilter": {
    "ods:predicateType": "and",
    "ods:hasPredicates": [
      {
        "ods:predicateType": "in",
        "ods:predicateKey": "$['ods:id']",
        "ods:predicateValues": ["https://doi.org/10.15468/holotype1", "https://doi.org/10.15468/holotype2"]
      },
      {
        "ods:predicateType": "not",
        "ods:predicateKey": "$['ods:organisationID']",
        "ods:predicateValue": "https://ror.org/0566bfb96"
      }
    ]
  }
}
